### ISSUE TITLE
First time setup, path to create an admin user

### ISSUE THREAD

**Issue by mbarlock** [punchcard-cms/punchcard#317] opened 2016-08-26 13:23 UTC
After successfully setting up punchcard there is no default admin account. There should be a path or initial setup step that will create an admin user

``` gherkin
Feature: Prompting to create an admin
  As a developer standing up punchcard
  I want to be prompted to create the first admin user
  So that I can log in and edit content without modifying the database directly

  Scenario: Developer stands up punchcard and goes to the root
    Given a brand new instance of punchcard
     When the user hits any route
     Then the user is prompted to create a new admin account
```

---

**Prompting to create an admin**
- [ ] Developer stands up punchcard and goes to the root

**Comment by scottnath** [comment] 2016-08-26 13:48
Hi @mbarlock, this is a known issue, but we don't have an issue for it written yet. Can you please submit a bug report according to our [contributing guidelines](https://github.com/punchcard-cms/punchcard/blob/master/CONTRIBUTING.md#issue-guidelines)?

In the meantime, run the unit tests after `npm install` by running `npm test`. When you do that, it creates a test admin user with [these credentials](https://github.com/punchcard-cms/punchcard/blob/master/tests/server.js#L17) for test purposes...but you can use that user to log in and create more users, including admins.

**Comment by Snugug** [comment] 2016-08-26 13:57
As this is a new feature, not a bug, please follow our contributing guidelines for requesting new functionality

**Comment by mbarlock** [comment] 2016-09-01 13:51
Updated! Took my best stab, at writing out the gherkin, leme know if I can do better

**Comment by Snugug** [comment] 2016-11-11 16:51
My feeling from a technical implementation perspective is that when a user is redirected to login, we check to see if if there are any users in the database, and if there are not, we change that form to a create user form

**Comment by scottnath** [comment] 2016-11-11 17:13
Sounds good.

Working on route middleware upgrades now.

**Comment by scottnath** [comment] 2016-11-16 20:11
This relies on the upgrades to the user's routing and model

**Comment by scottnath** [comment] 2016-11-17 15:29
blocked by #560

**Comment by scottnath** [comment] 2016-11-17 23:06
@mbarlock @Snugug 
fix is in!
https://github.com/punchcard-cms/punchcard/pull/572

**Closed** 2016-11-28 16:33 UTC
Labels: blocked, experience debt, feature, user experience
