### ISSUE TITLE
Input-Plugin-Reference

### ISSUE THREAD

**Issue by ayush2k** [punchcard-cms/punchcard#200] opened 2016-08-04 19:59 UTC
Need an input plugin for referencing one piece of content from another.

```gherkin
Feature: Input-Plugin-Reference
  As a core developer
  I want to implement an input plugin
  So that user may reference one piece of content to other

  Scenario: Reference one content type from all content types
     Given user wants to reference one content type
     When I implement an input plugin
     Then I should be able to indicate the number of references the user may choose
       
  Scenario: Reference a piece of content from one content type
    Given user wants to reference one piece of content
      And API supports retrieval of content
     When I implement an input plugin
     Then I should be able to indicate the content type
       And I should be able to indicate the number of references the user may choose
       And I should be able to indicate selection of content according to its state.

  Scenario: Reference a revision from one piece of content from one content type
     Given user wants to reference a revision from one piece of content
      And API supports retrieval of content
     When I implement an input plugin
     Then I should be able to indicate the content type
      And I should be able to indicate the content from the content type
      And I should be able to indicate the number of references the user may choose
      And I should be able to indicate selection of content according to its state.

  Scenario: Reference an attribute from one piece of content from one content type
     Given user wants to reference an attribute from one piece of content
      And API supports retrieval of content
     When I implement an input plugin
     Then I should be able to indicate the content type
      And I should be able to indicate the content from the content type
      And I should be able to indicate the number of references the user may choose
      And I should be able to indicate selection of content according to its state.

  Scenario: Reference an attribute from one revision of one piece of content from one content type
     Given user wants to reference an attribute from one revision of one piece of content
      And API supports retrieval of content
     When I implement an input plugin
     Then I should be able to indicate the content type
      And I should be able to indicate the content from the content type
      And I should be able to indicate the number of references the user may choose
      And I should be able to indicate selection of content according to its state.

```

---

**Input Plugin Reference**
- [ ] Input Plugin Reference / Reference one content type from all content types
- [ ] Input Plugin Reference / Reference a piece of content from one content type
- [ ] Input Plugin Reference / Reference a revision from one piece of content from one content type
- [ ] Input Plugin Reference / Reference an attribute from one piece of content from one content type
- [ ] Input Plugin Reference / Reference an attribute from one revision of one piece of content from one content type

**Comment by ayush2k** [comment] 2016-08-04 20:00
@scottnath @Snugug 
require some thoughts over state: 
* is it publishable?
* is it live?
* is it the latest revision?
* only content which has completed approval?
* unapproved content

**Comment by Snugug** [comment] 2016-08-16 13:25
Duplicate of https://github.com/punchcard-cms/punchcard/issues/45

**Closed** 2016-08-16 13:26 UTC
